### ISSUE TITLE
Criar o design do jogo

### ISSUE THREAD

**Issue by itsmevitinn** [42rio-projects/ft_transcendence#1]

**Comment by dvargas1** [comment]
https://www.figma.com/file/CTAwa8aLgVeNvK2nbwTkGn/Untitled?type=whiteboard&node-id=0%3A1&t=PZcTI9FdkourxLVP-1

**Comment by dvargas1** [comment]
Criei esse figma como uma forma de expressar a ideia, eu tenho dificuldade criativa de colocar as coisas direto no branco para visualizar como elas vao ficar, por isso esta com a base preta cheio de quadrado branco, mas nao precisa segui esse padrao em especifico, é só para ter algo a se guiar.
