### ISSUE TITLE
Implementar modulo ELK

### ISSUE THREAD

**Issue by dvargas1** [42rio-projects/ft_transcendence#78]
Issue para criar o modulo de ELK do PDF, ele vai seguir:

Deploy Elasticsearch to efficiently store and index log data, making it easily searchable and accessible.
  ◦ Configure Logstash to collect, process, and transform log data from various sources and send it to Elasticsearch.
  ◦ Set up Kibana for visualizing log data, creating dashboards, and generating insights from log events.
  ◦ Define data retention and archiving policies to manage the storage of log data effectively.
  ◦ Implement security measures to protect log data and access to the ELK stack components

**Comment by Leofariasrj25** [comment]
blocker

- [x] https and ssl certificate

**Comment by dvargas1** [comment]
FUCKING DONE
